export const products = [
	// Laptopy
	{
		name: "Dell XPS 15",
		description: "Wydajny laptop do pracy i multimediów.",
		categoryId: 1,
		price: 7999.99,
		imagePath: "/images/products/product1.jpg",
		details: "15,6-calowy ekran OLED, 16GB RAM, 1TB SSD",
		manufacturer: "Dell",
		model: "XPS 15",
		processor: "Intel Core i7-12700H",
		graphicsCard: "NVIDIA RTX 3060",
		operatingSystem: "Windows 11",
		batteryLife: "12h",
		screenSize: "15.6 cali",
		connectivity: "WiFi 6, Bluetooth 5.2",
	},
	{
		name: "MacBook Air M2",
		description: "Lekki i wydajny laptop od Apple.",
		categoryId: 1,
		price: 6999.99,
		imagePath: "/images/products/product2.jpg",
		details: "Czip M2, 16GB RAM, 512GB SSD",
		manufacturer: "Apple",
		model: "MacBook Air M2",
		processor: "Apple M2",
		graphicsCard: "Apple GPU 10-core",
		operatingSystem: "macOS Ventura",
		batteryLife: "18h",
		screenSize: "13.6 cali",
		connectivity: "WiFi 6, Bluetooth 5.3",
	},
	{
		name: "ASUS ROG Strix G15",
		description: "Gamingowy laptop z mocną kartą graficzną.",
		categoryId: 1,
		price: 8499.99,
		imagePath: "/images/products/product3.jpg",
		details: "Ryzen 7, RTX 3070, 32GB RAM, 1TB SSD",
		manufacturer: "ASUS",
		model: "ROG Strix G15",
		processor: "AMD Ryzen 7 6800H",
		graphicsCard: "NVIDIA RTX 3070",
		operatingSystem: "Windows 11",
		batteryLife: "10h",
		screenSize: "15.6 cali",
		connectivity: "WiFi 6E, Bluetooth 5.2",
	},
	{
		name: "Lenovo ThinkPad X1 Carbon",
		description: "Biznesowy laptop o lekkiej konstrukcji.",
		categoryId: 1,
		price: 9299.99,
		imagePath: "/images/products/product4.jpg",
		details: "Intel i7, 32GB RAM, 1TB SSD, 14-calowy ekran",
		manufacturer: "Lenovo",
		model: "ThinkPad X1 Carbon Gen 10",
		processor: "Intel Core i7-1260P",
		graphicsCard: "Intel Iris Xe",
		operatingSystem: "Windows 11 Pro",
		batteryLife: "14h",
		screenSize: "14 cali",
		connectivity: "WiFi 6E, Bluetooth 5.2",
	},
	{
		name: "HP Spectre x360",
		description: "Ultrabook 2w1 o wysokiej wydajności.",
		categoryId: 1,
		price: 7899.99,
		imagePath: "/images/products/product5.jpg",
		details: "Intel i7, 16GB RAM, 512GB SSD, dotykowy ekran",
		manufacturer: "HP",
		model: "Spectre x360",
		processor: "Intel Core i7-1255U",
		graphicsCard: "Intel Iris Xe",
		operatingSystem: "Windows 11",
		batteryLife: "13h",
		screenSize: "14 cali",
		connectivity: "WiFi 6E, Bluetooth 5.2",
	},

	// Smartphony
	{
		name: "iPhone 14 Pro",
		description: "Flagowy smartfon Apple z aparatem 48MP.",
		categoryId: 2,
		price: 6299.99,
		imagePath: "/images/products/product6.jpg",
		details: "A16 Bionic, 6GB RAM, 256GB, ProMotion 120Hz",
		manufacturer: "Apple",
		model: "iPhone 14 Pro",
		processor: "A16 Bionic",
		operatingSystem: "iOS 16",
		batteryLife: "20h",
		screenSize: "6.1 cali",
		connectivity: "5G, WiFi 6, Bluetooth 5.3",
	},
	{
		name: "Samsung Galaxy S23 Ultra",
		description: "Smartfon z aparatem 200MP i rysikiem S-Pen.",
		categoryId: 2,
		price: 7299.99,
		imagePath: "/images/products/product7.jpg",
		details: "Snapdragon 8 Gen 2, 12GB RAM, 512GB",
		manufacturer: "Samsung",
		model: "Galaxy S23 Ultra",
		processor: "Snapdragon 8 Gen 2",
		operatingSystem: "Android 13",
		batteryLife: "22h",
		screenSize: "6.8 cali",
		connectivity: "5G, WiFi 6E, Bluetooth 5.3",
	},

	// Tablety
	{
		name: "iPad Pro 12.9 (2022)",
		description: "Profesjonalny tablet z czipem M2.",
		categoryId: 3,
		price: 5899.99,
		imagePath: "/images/products/product8.jpg",
		details: "Czip M2, 8GB RAM, 256GB, 120Hz Liquid Retina",
		manufacturer: "Apple",
		model: "iPad Pro 12.9",
		processor: "Apple M2",
		operatingSystem: "iPadOS 16",
		batteryLife: "15h",
		screenSize: "12.9 cali",
		connectivity: "WiFi 6, Bluetooth 5.3",
	},

	// Smartwatche
	{
		name: "Apple Watch Series 8",
		description: "Inteligentny zegarek z EKG i czujnikiem temperatury.",
		categoryId: 4,
		price: 1999.99,
		imagePath: "/images/products/product9.jpg",
		details: "Always-On Display, wodoodporny, GPS",
		manufacturer: "Apple",
		model: "Watch Series 8",
		operatingSystem: "watchOS 9",
		batteryLife: "18h",
		screenSize: "1.9 cali",
		connectivity: "WiFi, Bluetooth 5.0",
	},
	{
		name: "Samsung Galaxy S22",
		description: "Smartwatch Samsung",
		categoryId: 4,
		price: 799.99,
		imagePath: "/images/products/product10.jpg",
		details: "Product description lorem ipsum dolor et lorem ipsum",
		manufacturer: "Samsung",
		model: "Galaxy S22",
		processor: "Snapdragon 8 Gen 1",
		operatingSystem: "Android 12",
		screenSize: "6.1",
	},
	{
		name: "Garmin Fenix 6",
		description: "Sportowy smartwatch",
		categoryId: 4,
		price: 599.99,
		imagePath: "/images/products/product11.jpg",
		details: "Product description lorem ipsum dolor et lorem ipsum",
		manufacturer: "Garmin",
		model: "Fenix 6",
		batteryLife: "14 dni",
		operatingSystem: "Garmin OS",
	},
	{
		name: "Fitbit Versa 3",
		description: "Smartwatch Fitbit",
		categoryId: 4,
		price: 229.99,
		imagePath: "/images/products/product12.jpg",
		details: "Product description lorem ipsum dolor et lorem ipsum",
		manufacturer: "Fitbit",
		model: "Versa 3",
		batteryLife: "6 dni",
		operatingSystem: "Fitbit OS",
	},
	{
		name: "Huawei Watch GT 3",
		description: "Smartwatch Huawei",
		categoryId: 4,
		price: 199.99,
		imagePath: "/images/products/product13.jpg",
		details: "Product description lorem ipsum dolor et lorem ipsum",
		manufacturer: "Huawei",
		model: "Watch GT 3",
		batteryLife: "14 dni",
		operatingSystem: "HarmonyOS",
	},
	{
		name: "Xiaomi Mi Watch",
		description: "Smartwatch Xiaomi",
		categoryId: 4,
		price: 149.99,
		imagePath: "/images/products/product14.jpg",
		details: "Product description lorem ipsum dolor et lorem ipsum",
		manufacturer: "Xiaomi",
		model: "Mi Watch",
		batteryLife: "16 dni",
		operatingSystem: "MIUI Watch OS",
	},

	// Słuchawki bezprzewodowe
	{
		name: "Sony WH-1000XM5",
		description: "Słuchawki z najlepszą redukcją hałasu.",
		categoryId: 5,
		price: 1799.99,
		imagePath: "/images/products/product15.jpg",
		details: "ANC, 40h pracy na baterii, LDAC",
		manufacturer: "Sony",
		model: "WH-1000XM5",
		batteryLife: "40h",
		connectivity: "Bluetooth 5.2",
	},
	{
		name: "Sony WH-1000XM4",
		description: "Bezprzewodowe słuchawki",
		categoryId: 5,
		price: 299.99,
		imagePath: "/images/products/product16.jpg",
		details: "Product description lorem ipsum dolor et lorem ipsum",
		manufacturer: "Sony",
		model: "WH-1000XM4",
		batteryLife: "30h",
		connectivity: "Bluetooth 5.0",
	},
	{
		name: "AirPods Pro",
		description: "Bezprzewodowe słuchawki Bose",
		categoryId: 5,
		price: 249.99,
		imagePath: "/images/products/product17.jpg",
		details: "Product description lorem ipsum dolor et lorem ipsum",
		manufacturer: "Apple",
		model: "Pro",
		batteryLife: "24h",
		connectivity: "Bluetooth 5.0",
	},
	{
		name: "Bose 700",
		description: "Słuchawki Apple",
		categoryId: 5,
		price: 379.99,
		imagePath: "/images/products/product18.jpg",
		details: "Product description lorem ipsum dolor et lorem ipsum",
		manufacturer: "Bose",
		model: "700",
		batteryLife: "20h",
		connectivity: "Bluetooth 5.0",
	},

	// Słuchawki przewodowe
	{
		name: "Sennheiser HD 600",
		description: "Referencyjne słuchawki przewodowe.",
		categoryId: 6,
		price: 1599.99,
		imagePath: "/images/products/product19.jpg",
		details: "Dźwięk Hi-Fi, przetworniki 300Ω",
		manufacturer: "Sennheiser",
		model: "HD 600",
		connectivity: "Przewodowe (Jack 3.5mm)",
	},
	{
		name: "FiiO FT1",
		description: "Słuchawki przewodowe nauszne.",
		categoryId: 6,
		price: 849.0,
		imagePath: "/images/products/product20.jpg",
		details: "Dźwięk Hi-Fi, przetworniki 300Ω",
		manufacturer: "FiiO",
		model: "FT1",
		connectivity: "TRS 3.5 mm, Pentaconn 4,4 mm",
	},
];
