export const products = [
	{
		name: "Sony WH-1000XM4",
		description: "Bezprzewodowe słuchawki",
		categoryId: 5,
		price: 299.99,
		imagePath: "/images/products/headphones.png",
		details: "Product description lorem ipsum dolor et lorem ipsum",
		manufacturer: "Sony",
		model: "WH-1000XM4",
		batteryLife: "30h",
		connectivity: "Bluetooth 5.0",
	},
	{
		name: "AirPods Pro",
		description: "Bezprzewodowe słuchawki Bose",
		categoryId: 5,
		price: 249.99,
		imagePath: "/images/products/earbuds.png",
		details: "Product description lorem ipsum dolor et lorem ipsum",
		manufacturer: "Apple",
		model: "Pro",
		batteryLife: "24h",
		connectivity: "Bluetooth 5.0",
	},
	{
		name: "Bose 700",
		description: "Słuchawki Apple",
		categoryId: 5,
		price: 379.99,
		imagePath: "/images/products/airpods.png",
		details: "Product description lorem ipsum dolor et lorem ipsum",
		manufacturer: "Bose",
		model: "700",
		batteryLife: "20h",
		connectivity: "Bluetooth 5.0",
	},
	{
		name: "Apple Watch Series 7",
		description: "Smartwatch Apple",
		categoryId: 4,
		price: 399.99,
		imagePath: "/images/products/watch-red.png",
		details: "Product description lorem ipsum dolor et lorem ipsum",
		manufacturer: "Apple",
		model: "Series 7",
		batteryLife: "18h",
		operatingSystem: "watchOS",
	},
	{
		name: "Samsung Galaxy Watch 4",
		description: "Smartwatch Samsung",
		categoryId: 4,
		price: 249.99,
		imagePath: "/images/products/smartwatch-black.png",
		details: "Product description lorem ipsum dolor et lorem ipsum",
		manufacturer: "Samsung",
		model: "Watch 4",
		batteryLife: "40h",
		operatingSystem: "Wear OS",
	},
	{
		name: "Garmin Fenix 6",
		description: "Sportowy smartwatch",
		categoryId: 4,
		price: 599.99,
		imagePath: "/images/products/watch-white.png",
		details: "Product description lorem ipsum dolor et lorem ipsum",
		manufacturer: "Garmin",
		model: "Fenix 6",
		batteryLife: "14 dni",
		operatingSystem: "Garmin OS",
	},
	{
		name: "Fitbit Versa 3",
		description: "Smartwatch Fitbit",
		categoryId: 4,
		price: 229.99,
		imagePath: "/images/products/smartwatch-blue.png",
		details: "Product description lorem ipsum dolor et lorem ipsum",
		manufacturer: "Fitbit",
		model: "Versa 3",
		batteryLife: "6 dni",
		operatingSystem: "Fitbit OS",
	},
	{
		name: "Huawei Watch GT 3",
		description: "Smartwatch Huawei",
		categoryId: 4,
		price: 199.99,
		imagePath: "/images/products/iphone.png",
		details: "Product description lorem ipsum dolor et lorem ipsum",
		manufacturer: "Huawei",
		model: "Watch GT 3",
		batteryLife: "14 dni",
		operatingSystem: "HarmonyOS",
	},
	{
		name: "Xiaomi Mi Watch",
		description: "Smartwatch Xiaomi",
		categoryId: 4,
		price: 149.99,
		imagePath: "/images/products/watch-gray.png",
		details: "Product description lorem ipsum dolor et lorem ipsum",
		manufacturer: "Xiaomi",
		model: "Mi Watch",
		batteryLife: "16 dni",
		operatingSystem: "MIUI Watch OS",
	},
	{
		name: "Samsung Galaxy S22",
		description: "Smartwatch Samsung",
		categoryId: 2,
		price: 799.99,
		imagePath: "/images/products/smartwatch-apps.png",
		details: "Product description lorem ipsum dolor et lorem ipsum",
		manufacturer: "Samsung",
		model: "Galaxy S22",
		processor: "Snapdragon 8 Gen 1",
		operatingSystem: "Android 12",
		screenSize: "6.1",
	},
];
